Documentation
LucRome/SWE_Semester4 pull request #56
Opened 2021-04-22 09:56 UTC by haasmi

Please only merge after spelling correction

2021-04-22 10:09 UTC, 43-50ph14 reviewed
s. Kommentare
rechtschreibung sollte nochmal wer anders reviewn

2021-04-22 10:09 UTC, 43-50ph14 commented on SWE_Doc/Lastenheft/content/chapter/03.tex
> +\item bearbeitete Abgaben von Studenten einsehen und herunterladen
nur herunterladen, nicht einsehen

2021-04-22 10:09 UTC, 43-50ph14 commented on SWE_Doc/Lastenheft/content/chapter/03.tex
> +\item zur Verfügung stehende Aufgaben einsehen und herunterladen
s.o.

2021-04-22 10:09 UTC, 43-50ph14 commented on SWE_Doc/Lastenheft/content/chapter/03.tex
> +\item korrigierte Abgaben einsehen
ich würde herunterladen sagen

2021-04-22 10:09 UTC, 43-50ph14 commented on SWE_Doc/Lastenheft/content/chapter/03.tex
> +\begin{itemize}
bewertungen freischalten? war mal geplant

2021-04-22 10:09 UTC, 43-50ph14 commented on SWE_Doc/Lastenheft/content/chapter/03.tex
> +Anmerkung: Studierende sollen Bewertungen von Aufgaben erst dann einsehen, wenn diese von einem Administrator freigeschaltet wurden
dann bitte auch oben bei den aktionen ergänzen

2021-04-22 10:09 UTC, 43-50ph14 commented on SWE_Doc/Lastenheft/content/chapter/03.tex
> +\item Ein*e Dozent*in wird nach einer definierten Zeit automatisch an die Bewertung von Abgaben erinnert
das ist nicht richtig gegendert

2021-04-22 10:09 UTC, 43-50ph14 commented on SWE_Doc/Lastenheft/main.tex
> +	%\cleardoublepage
das einfach löschen anstatt auszukommentieren wäre ordentlicher

2021-04-22 10:09 UTC, 43-50ph14 commented on SWE_Doc/Lastenheft/main.tex
> +	%\listoffigures
s.o

2021-04-22 10:09 UTC, 43-50ph14 commented on SWE_Doc/Lastenheft/main.tex
> +	%\printglossary[style=altlist,title=\glossaryPhrase]
s.o

2021-04-22 10:09 UTC, 43-50ph14 commented on SWE_Doc/Lastenheft/main.tex
> +	%\appendix
s.o

2021-04-27 14:17 UTC, 43-50ph14 approved these changes
ok

2021-04-27 14:18 UTC, codingHahn requested changes
Delete se pdf!!!111!!1!!!11!!111!

2021-04-27 15:10 UTC, codingHahn approved these changes
Please squash and meaningful commit message

2021-04-27 16:51 UTC, merged