Forms labels
LucRome/SWE_Semester4 pull request #99
Opened 2021-05-11 21:43 UTC by LucRome

2021-05-13 07:28 UTC, 43-50ph14 requested changes
looks good overall, please address the comments

2021-05-13 07:28 UTC, 43-50ph14 commented on eCourse_backend/courses/urls.py
> +    path('detailed', detailed_course, name='detailed_course'),
should be detailed/<id> but i don't know if we need this still. This was originally created by backend to demonstrate the function. I think you created another template?

2021-05-13 07:28 UTC, 43-50ph14 commented on eCourse_backend/courses/views.py
> +            'files': files}
files have moved to fileexchange/views.py

2021-05-13 07:28 UTC, 43-50ph14 commented on eCourse_backend/courses/views.py
> +                (Q(user=request.user.id) | Q(from_lecturer=1)), exercise=e.id)
files have moved to fileexchange/views.py

2021-05-13 20:34 UTC, LucRome commented
**Warning:**
    * already contains the changes made in design rework
    * only files that are important for this PR are the `forms.py`

2021-05-13 20:36 UTC, LucRome commented
Changes: Added the field `labels={...}` to the model forms, and removed one obsolete function (from `users/forms.py`

2021-05-13 21:34 UTC, LucRome commented on eCourse_backend/templates/home/home_auth.html
> -      )
Necessary, otherwise it puts a space before ')'
Example: `(Gruppe: Dozenten )`

Bugs me out

2021-05-14 07:44 UTC, 43-50ph14 approved these changes
:+1:

2021-05-14 13:38 UTC, merged